In [1]:
import pandas as pd
import numpy as np

In [2]:
from preprocessing import preprocessing

In [3]:
housing = pd.read_csv("files/housing.csv")
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [4]:
preprocessing.fit_transform(housing)

C:\Python\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Python\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[-1.02998783,  0.62855945, -0.04959654, ...,  1.        ,
         0.        , -0.46159535],
       [-0.8888972 ,  0.32704136, -0.09251223, ...,  1.        ,
         0.        , -0.54597267],
       [-1.29168566,  1.15562047, -0.02584253, ...,  1.        ,
         0.        , -0.54597268],
       ...,
       [ 0.02113407, -0.09031802, -0.0717345 , ...,  0.        ,
         0.        , -0.54597268],
       [ 0.09346655, -0.04021111, -0.09122515, ...,  0.        ,
         0.        , -0.54597268],
       [ 0.11327519, -0.07044252, -0.04368215, ...,  0.        ,
         0.        , -0.54597268]])

In [5]:
preprocessing.get_feature_names_out()

array(['bedrooms__ratio', 'rooms_per_house__ratio',
       'people_per_house__ratio', 'log__total_bedrooms',
       'log__total_rooms', 'log__population', 'log__households',
       'log__median_income', 'geo__similarity with 1 cluster',
       'geo__similarity with 2 cluster', 'geo__similarity with 3 cluster',
       'geo__similarity with 4 cluster', 'geo__similarity with 5 cluster',
       'geo__similarity with 6 cluster', 'geo__similarity with 7 cluster',
       'geo__similarity with 8 cluster', 'geo__similarity with 9 cluster',
       'geo__similarity with 10 cluster',
       'cat__ocean_proximity_<1H OCEAN', 'cat__ocean_proximity_INLAND',
       'cat__ocean_proximity_ISLAND', 'cat__ocean_proximity_NEAR BAY',
       'cat__ocean_proximity_NEAR OCEAN',
       'simil__Similarity With Housing age: 35'], dtype=object)